### PR TITLE
Feature/zd24483 cutom play by play events by categories

### PR DESCRIPTION
**Pull request by firelf15**
OK, I have no idea what to do with the "Can't automatically merge" stuff. Should I pull the Master a rebase?

### CODE REVIEW

**Comment by rockymountainhigh1943** [comment]
Hi @firelf15,

So it looks like we might have some issues with this PR -- especially with all the merge conflicts. This is what I recommend doing:

1. Pull down the latest into your local master branch (switch to master, `git pull origin master`)
2. Switch to this branch on your local (`git checkout feature/zd24483-cutom-play-by-play-events-by-categories`)
3. Merge master into this branch (`git merge master`)
4. At this point you should still see merge conflicts, but now you should run the default grunt task (`grunt`) -- this should rebuild all the template files and compile SASS again to clear out the merge conflicts. After this you might run `git diff --name-only --diff-filter=U` to see if any conflicts still show up.
5. Once that completes -- run `grunt patternlab:cswatch` -- then when PatternLab opens -- run through a bunch of the "Pages" to make sure everything is still working and looks correct (especially the new items you added).
6. Then commit all these changes -- and push back up to this branch to update the PR

Let me know if you have any questions with this or would want to run through this together.

Thanks!
Jake

**Comment by firelf15** [comment]
In step 4, after running the default grunt command, "git diff --name-only --diff-filter=U " still results in loads and loads of .map and .html files. Is that to be expected?

**Comment by firelf15** [comment]
screen shot 2017-08-10 at 5 46 02 pm
I bailed out on the merge and went back to the master branch... is what's shown in the attached screenshot to be expected?

**Comment by rockymountainhigh1943** [comment]
Hi @firelf15,

So it looks like from your screen shot -- that after pulling master you didn't switch to your feature branch and merge in master there. I think that is where you missed the step.

You're going to either need to checkout those changes on your master branch, reset that branch to master, or stash the changes. Then you would need to run through those steps above again. 

Let me know if you'd like to run through this together tomorrow and we can go form there.

Thanks,
Jake

**Comment by firelf15** [comment]
Well, the screenshot is from a completely clean, up-to-date Master, no changes of mine at all. I wouldn't have expected running grunt to change all those files since they're compiled in the repo?

**Comment by rockymountainhigh1943** [comment]
Hi @firelf15,

The reason the grunt task changes files whenever it runs is because it adds cache breakers based on the date. So in this case, I would reset your master branch and start over with the steps listed above.

You can reset your master branch by doing the following:

1. Make sure you're on the master branch `git checkout master`
2. Fetch the latest origin ref `git fetch origin`
3. Then reset `git reset --hard origin/master`
4. Run `git status` and make sure you have reset correctly and there are no changes

Once this is done -- continue with my initial directions at **step 2** (since you now have the latest from master). This means you run `git checkout feature/zd24483-cutom-play-by-play-events-by-categories`, and then run `git merge master` and continue on to **step 4**.

If you're still having issues with these steps we can run through this together first thing on Monday.

Thanks!
Jake

**Comment by firelf15** [comment]
git diff --name-only --diff-filter=U still gives a boat-load of results; .map and .html files

**Comment by firelf15** [comment]
see story on a different computer with brand new clone of the repo... My command line history
306  mkdir sandbox
307  cd sandbox
308  git clone git@github.com:Entercom/frequency-nts-theme.git
309  git pull origin master
310  cd frequency-nts-theme
311  git pull origin master
312  git checkout feature/zd24483-cutom-play-by-play-events-by-categories
313  git merge master
314  grunt
315  npm install
316  grunt
317  bower install
318  grunt
319  git diff --name-only --diff-filter=U

Looking at a few git diffs on the boat-load of files listed as a result of "git diff --name-only --diff-filter=U" they all appear to be the cache-breaking things you mentioned.
e.g.
-      var cb = '1501626664435';
+      var cb = '1502495482374';

Maybe there's something better to look at than "git diff --name-only --diff-filter=U" because I've followed the directions a number of times with the same results.

**Pull request merged**
